title: "Ana"
author: "Ana Raquel Campesan"
description: "Software Developer"
more: "read more"
url: "https://anazard.me"
permalink: none

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Styles
sass:
  sass_dir: ./css
